deployments:
  - path: namespace
  - barrier: true
  - path: manifest
    vars:
      - clusterConfigMap:
          name: ingress
          namespace: homelab-config
          key: vars
        targetPath: ingress