---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mailserver
  name: maddydata
  namespace: mailserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
