apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lldap-user
  namespace: mailserver
  labels:
    app: mailserver
data:
  username: {{ lldap_user.username }}
  password: {{ lldap_user.password }}
