---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lldap-jwt
  namespace: lldap
  labels:
    app: lldap
  annotations:
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/autogenerate: jwt-secret
stringData: {}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lldap-admin
  namespace: lldap
  labels:
    app: lldap
  annotations:
    secret-generator.v1.mittwald.de/length: "20"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: admin
---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: "lldap-reader"
  namespace: "lldap"
spec:
  forceRegenerate: false
  data:
    username: "reader"
  fields:
    - fieldName: "password"
      length: "20"