apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
        - name: authelia
          # See https://github.com/authelia/authelia/pkgs/container/authelia/versions?filters%5Bversion_type%5D=tagged
          image: ghcr.io/authelia/authelia:4.38.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          args:
            - '--config=/configuration.yaml'
          command:
            - authelia
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
            - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
              value: 'true'
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /secrets/JWT_TOKEN
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /secrets/SESSION_ENCRYPTION_KEY
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
              value: /secrets/LDAP_PASSWORD
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /secrets/STORAGE_ENCRYPTION_KEY
          startupProbe:
            failureThreshold: 6
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /configuration.yaml
              name: config
              readOnly: true
              subPath: configuration.yaml
            - mountPath: /secrets
              name: secrets
              readOnly: true
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      volumes:
        - configMap:
            items:
              - key: configuration.yaml
                path: configuration.yaml
            name: authelia-config
          name: config
        - name: secrets
          secret:
            items:
              - key: JWT_TOKEN
                path: JWT_TOKEN
              - key: SESSION_ENCRYPTION_KEY
                path: SESSION_ENCRYPTION_KEY
              - key: STORAGE_ENCRYPTION_KEY
                path: STORAGE_ENCRYPTION_KEY
              - key: LDAP_PASSWORD
                path: LDAP_PASSWORD
            secretName: authelia-secrets
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate