apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: authelia-secrets
  namespace: authelia
  labels:
    app: authelia
spec:
  forceRegenerate: false
  data:
    LDAP_PASSWORD: {{ lldap_user.password | b64decode }}
  fields:
    - fieldName: JWT_TOKEN
      encoding: "base64"
      length: "32"
    - fieldName: SESSION_ENCRYPTION_KEY
      encoding: "base64"
      length: "32"
    - fieldName: STORAGE_ENCRYPTION_KEY
      encoding: "base64"
      length: "32"
