deployments:
  - path: namespace
  - barrier: true
  - path: cert-manager
  - barrier: true
  - path: cert-issuer
    vars:
      - clusterObject:
          kind: Secret
          name: cloudflare
          namespace: homelab-config
          path: data
        targetPath: cloudflare
      - clusterObject:
          kind: Secret
          name: zerossl
          namespace: homelab-config
          path: data
        targetPath: zerossl
