deployments:
  - path: namespace
  - barrier: true
  - include: kluctl
  - path: metallb
  - path: cert-manager
  - barrier: true
  #- path: gitops # TODO: figure out why this gets blocked
  - path: metallb-config
    vars:
      - clusterConfigMap:
          name: lbconfig
          namespace: homelab-config
          key: vars
        targetPath: lbconfig
  - barrier: true
  - path: cert-issuer
    vars:
      - clusterSecret:
          name: cloudflare
          namespace: homelab-config
          key: email
        targetPath: cloudflare.email
      - clusterSecret:
          name: cloudflare
          namespace: homelab-config
          key: api-token
        targetPath: cloudflare.api-token
  - path: ingress-nginx
    vars:
      - clusterConfigMap:
          name: lbconfig
          namespace: homelab-config
          key: vars
        targetPath: lbconfig

commonLabels:
  examples.kluctl.io/deployment-project: "clusterinfra"

conflictResolution:
  - kind: ValidatingWebhookConfiguration
    namespace: metallb-system
    fieldPath: webhooks.*.*
    action: ignore
  - kind: CustomResourceDefinition
    fieldPathRegex: ".*\\.caBundle.*"
    action: ignore