deployments:
  - path: namespace
  - barrier: true
  - include: kluctl
  - path: metallb
  - path: cert-manager
  - path: openebs
  - barrier: true
  #- path: gitops # TODO: figure out why this gets blocked
  - path: metallb-config
    vars:
      - clusterConfigMap:
          name: lbconfig
          namespace: homelab-config
          key: vars
        targetPath: lbconfig
  - barrier: true
  - path: cert-issuer
    vars:
      - clusterObject:
          kind: Secret
          name: cloudflare
          namespace: homelab-config
          path: data
        targetPath: cloudflare
  - path: openebs-config
  - path: inadyn
    vars:
      - clusterObject:
          kind: Secret
          name: cloudflare
          namespace: homelab-config
          path: data
        targetPath: cloudflare
  - path: ingress-nginx
    vars:
      - clusterConfigMap:
          name: lbconfig
          namespace: homelab-config
          key: vars
        targetPath: lbconfig

commonLabels:
  examples.kluctl.io/deployment-project: "clusterinfra"

conflictResolution:
  - kind: CustomResourceDefinition
    fieldPathRegex: ".*\\.caBundle.*"
    action: ignore