deployments:
  - path: namespace
  - barrier: true
  - include: kluctl
  - path: metallb
  - path: cert-manager
  - barrier: true
  - path: gitops

commonLabels:
  examples.kluctl.io/deployment-project: "clusterinfra"

conflictResolution:
  - kind: ValidatingWebhookConfiguration
    namespace: metallb-system
    fieldPath: webhooks.*.*
    action: ignore
