controller:
  ingressClassResource:
    default: "true"
  allowSnippetAnnotations: "true"
  service:
    loadBalancerIP: {{ lbconfig.clusterip }}
    annotations:
      "metallb.universe.tf/allow-shared-ip": "cluster"