---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lldap-jwt
  namespace: lldap
  labels:
    app: lldap
  annotations:
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/autogenerate: jwt-secret
stringData: {}
