deployments:
  - path: namespace
  - barrier: true
  - path: manifest
    vars:
      - clusterConfigMap:
          name: ingress
          namespace: homelab-config
          key: vars
        targetPath: ingress
      - clusterConfigMap:
          name: ldap
          namespace: homelab-config
          key: vars
        targetPath: ldap
      - clusterObject:
          kind: Secret
          name: lldap-reader
          namespace: lldap
          path: data
        targetPath: lldap_user

overrideNamespace: mealie