apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config
  namespace: inadyn
stringData:
  inadyn.conf: |-
    # Create a unique custom API token with the following permissions:
    # -> Zone.Zone - Read, Zone.DNS - Edit.
    provider cloudflare.com {
        username = {{ cloudflare.domain | b64decode }}
        password = {{ cloudflare["api-token"] | b64decode }}
        hostname = {{ cloudflare.domain | b64decode }}
    }