apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mealie
  name: mealie
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 9000
  selector:
    io.kompose.service: mealie
