apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
data:
  email: {{ cloudflare.email }}
  api-token: {{ cloudflare["api-token"] }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager # Must be the namespace cert-manager is installed in
  name: zerossl-eab
data:
  eab: {{ zerossl.eab }}
  hmac: {{ zerossl.hmac }}