apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: inadyn
data:
  inadyn.conf: |-
    # Create a unique custom API token with the following permissions:
    # -> Zone.Zone - Read, Zone.DNS - Edit.
    provider cloudflare.com {{ "{{" }}
        username = {{ cloudflare.domain }}
        password = {{ cloudflare["api-token"] }}
        hostname = {{ cloudflare.domain }}
    {{ "}}" }}